openapi: 3.0.0
info:
  title: bg-openapi3
  version: '1.0'
  description: adadsdsdssdsd
  contact:
    name: name
    url: url.com
    email: sdssd
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas: {}
  securitySchemes:
    API Key - 1:
      name: API Key
      type: apiKey
      in: query
